### ISSUE TITLE
ox.consolidate_intersections in stop_hotspots notebooks returns TypeError: sjoin() got an unexpected keyword argument 'predicate' error

### ISSUE THREAD

**Issue by MaryamGolchin** [anitagraser/movingpandas-examples#16]
![image](https://user-images.githubusercontent.com/85209561/204127537-73fb9654-411f-4a07-9b04-c5d200a57f8b.png)

Name                  Version                   Build              
osmnx                     1.2.2              pyhd8ed1ab_0    
geopandas                 0.9.0                      py_1 
networkx                  2.8.4            py38haa95532_0 
pysal                     2.3.0                      py_0

Operator: Windows10
IDE: VSCode

**Comment by anitagraser** [comment]
Hi Maryam, 

I just tested the [stop hotspots notbeook on mybinder](https://mybinder.org/v2/gh/anitagraser/movingpandas-examples/main?filepath=3-tech-demos/stop-hotspots.ipynb) but cannot reproduce this issue. 

![image](https://user-images.githubusercontent.com/590385/204151955-9f84579a-6366-4057-a5f2-fdd4832cbbf7.png)

![image](https://user-images.githubusercontent.com/590385/204151987-4bf2102b-47f1-4aff-8550-0554bba3aa6d.png)

![image](https://user-images.githubusercontent.com/590385/204152028-c9a80354-7b01-4e72-a706-5cf80a6ac5b6.png)

**Comment by MaryamGolchin** [comment]
Thanks for your prompt reply. The issue was resolved after updating the geopandas library to 0.12.1 version.
